title: Java Core Principles - Spring Preparation Guide
description: A comprehensive reference guide covering essential Java concepts needed to master Spring Framework
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: Java Spring Fundamentals Guide
social:
  type: Organization
  links:
    - https://github.com/Omar-Mega-Byte/java-fundamentals-for-spring

# GitHub Pages settings
repository: Omar-Mega-Byte/java-fundamentals-for-spring
github:
  owner_name: Omar-Mega-Byte
  repository_name: java-fundamentals-for-spring

# Additional settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections (if you want to organize modules as collections)
collections:
  modules:
    output: true
    permalink: /:collection/:name/

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - package.json
  - package-lock.json
